# Site settings 配置站点
title: 'cymok' # your awesome title
description: '我的代码没有bug'
keywords: 'Android, Java, Python' # your web keywords, another keywords
url: 'https://cymok.github.io' # your host

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  首页: '/'
  标签: '/tags.html'
  时间线: '/timeline.html'
  关于博主: '/about.html'
 # 友情链接: '/friendLink.html'
  个人简历: '/resume/resume.pdf'

# 博主
author: true
name: 'Mok Chiyin'
NickName: 'Harry'
webtitle: '个人博客blog'
bio: '24, boy'
about: true
aboutyou: '来自广东一个遥远的小村庄嘅一个boy，从第一次去网吧开始就爱上计算机。只有0和1的世界是多么的神奇、奥秘，而这注定是一条不归路。。。'
# portraits: '/assets/profile.jpeg' # your portraits image file path
portraits: 'https://avatars0.githubusercontent.com/u/27819746?s=460&v=4' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'mailto:mozhx020@163.com'
  weixin: '/assets/qr_code_wechat.jpg' # 你的微信二维码存放的地址
  qq: 'http://wpa.qq.com/msgrd?v=3&uin=604193275&site=qq&menu=yes' # 你的qq二维码存放的地址 or http://wpa.qq.com/msgrd?v=3&uin='你的QQ号'&site=qq&menu=yes
  github: 'https://github.com/cymok'
 # Codepen: ''
 # weibo: ''
 # instagram: ''
  Facebook: 'http://facebook.com/mozhx'
  Twitter: 'http://twitter.com/MokChiyin'
 # Dribbble: ''
 # Google: ''
 # zhihu: ''
 # juejin: ''
 # twitch: ''

# 分页
paginate: 10
paginatepath: ['page:num']

# since
footer:
  since: 2017

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'default'

# 友情链接
friends:
  jekyll: 'https://www.jekyll.com.cn/'

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: true
livere_uid: 'MTAyMC80NjQ0NS8yMjk1Ng==' # 'MTAyMC80NjQ0NC8yMjk1NQ==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github用户名
Gitment_repo: ''  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: true
baidu-url: ''
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: false
google-ID: ''

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
